[package]
name = "compiler-bf-target"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] } 
logos = "0.16.0"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.17"
