
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    volumes:
      - ./src:/app/src
      - ./web-frontend:/app/web-frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./web-frontend:/app/web-frontend
    depends_on:
      - backend
    environment:
      - CI=true
